cask "aeroshift" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.0.9'
  sha256 "8674523a3dd0ebbd032d3f88d513cebb4c93f4228154bc9630bb2d170fd25f83"

  url "https://github.com/Boredphilosopher96/AeroShift/releases/download/v#{version}/Aeroshift-v#{version}.zip"
  name "Aeroshift"
  desc "Unofficial fork of AeroSpace, an i3-like tiling window manager for macOS"
  homepage "https://github.com/Boredphilosopher96/Aeroshift"
  conflicts_with cask: ['aeroshift-dev']

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{staged_path}/Aeroshift-v#{version}/bin/aeroshift"
    system "xattr -d com.apple.quarantine #{appdir}/Aeroshift.app"
  end

  app "Aeroshift-v#{version}/Aeroshift.app"
  binary "Aeroshift-v#{version}/bin/aeroshift"

  binary "Aeroshift-v#{version}/shell-completion/zsh/_aeroshift",
      target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_aeroshift"
  binary "Aeroshift-v#{version}/shell-completion/bash/aeroshift",
      target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/aeroshift"
  binary "Aeroshift-v#{version}/shell-completion/fish/aeroshift.fish",
      target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/aeroshift.fish"

  Dir["#{staged_path}/Aeroshift-v#{version}/manpage/*"].each { |man| manpage man }
end
